# Base image
ARG base_image_handle

FROM "${base_image_handle}"

# Build arguments
ARG user_name
ARG work_dir

ARG group_name="${user_name}"
ARG group_id='1000'
ARG user_id='1000'

# Set up non-system user
RUN addgroup \
      --gid "${group_id}" \
      "${group_name}" \
      && adduser \
      --uid "${user_id}" \
      --disabled-password \
      --ingroup "${group_name}" \
      "${user_name}"

# Set environment variables
ENV HOME "/home/${user_name}"
ENV USER "${user_name}"

# Set non-system user
USER "${USER}"

# Create working directory as a non-system user
RUN mkdir "${HOME}/${work_dir}"

# Change to working directory
WORKDIR "${HOME}/${work_dir}"

# Copy source code as a non-system user
COPY \
  --chown=${user_name}:${group_name} \
  . "${HOME}/${work_dir}"

# Runtime entrypoint
ENTRYPOINT ["/bin/sh"]
